version: '3.4'

services:
  surveyhos.web:
    image: ${DOCKER_REGISTRY-}surveyhosweb
    build:
      context: .
      dockerfile: SurveyHos.Web/Dockerfile
    networks:
      - db_postgres
networks:
  db_postgres:
    external: true